name: Create Booklet
run-name: ${{ github.actor }} initializing booklet 
on: [push]
jobs:
  Init-BookLet:
    runs-on: ubuntu-latest
    steps:
      - run: echo "ğŸ” The name of your branch is ${{ github.ref }} and your repository is ${{ github.repository }}."
      
      - name: Check out repository code in undefied branch
        uses: actions/checkout@v3
        with:
          ref: booklet
      - run: echo "ğŸ’¡ The ${{ github.repository }} repository has been cloned to the runner."
      - run: echo "ğŸ–¥ï¸ The workflow is now ready to test your code on the runner."
      - name: List files in the repository
        run: |
          ls ${{ github.workspace }}
      - run: echo "ğŸ This job's status is ${{ job.status }}."
