name: Create Booklet
run-name: ${{ github.actor }} initializing booklet 
on: [push]
jobs:
  Init-BookLet:
    runs-on: ubuntu-latest
    steps:
      - run: echo "ğŸ” The name of your branch is ${{ github.ref }} and your repository is ${{ github.repository }}."
      
      - name: Check out repository
        uses: actions/checkout@v3
      - run: echo "ğŸ’¡ The ${{ github.repository }} repository has been cloned to the runner."
      - name: List files in the repository
        run: |
          cd ${{ github.workspace }}
          git checkout -b booklet
          git push -u origin booklet
      - run: echo "ğŸ This job's status is ${{ job.status }}."
